name: 'Nightly Zephyr Tests'
description: 'Runs a test application for a SoC.'
inputs:
  board:
    description: 'Name of the Zephyr board name like hydrogen1-nexys4ddr'
    required: true
  application:
    description: 'Name of the test application like mtimer'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build
      run: |
        west build -p always -b ${{ inputs.board }} elements-zephyr-application/app/test/${{ inputs.application }}
      shell: bash
      working-directory: zephyr/
    - name: Test
      run: |
        west test ${{ inputs.application }}
      shell: bash
      working-directory: zephyr/
    - name: Remove build
      run: |
         rm -rf build/
      shell: bash
      working-directory: zephyr/
