version: "2"
services:
  sdk:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - build:/elements-sdk/build/
# Uncomment to use Xilinx toolchain
#      - <path to vivado installation dir>/Vivado/:/opt/xilinx/Vivado/
# Uncomment if different environment variables are used
#      - ./env.ini:/elements-sdk/env.ini
# Uncomment to forward local changes
#      - ./base.py:/elements-sdk/base.py
#      - ./elements.py:/elements-sdk/elements.py
#      - ./elements-fpga.py:/elements-sdk/elements-fpga.py
#      - ./elements-asic.py:/elements-sdk/elements-asic.py
#      - ./internal/embench-iot/:/elements-sdk/internal/embench-iot/
#      - ./internal/nafarr/:/elements-sdk/internal/nafarr/
#      - ./internal/openocd/:/elements-sdk/internal/openocd/
#      - ./internal/SpinalCrypto/:/elements-sdk/internal/SpinalCrypto/
#      - ./internal/vexriscv/:/elements-sdk/internal/vexriscv/
#      - ./internal/zephyr/:/elements-sdk/internal/zephyr/
#      - ./internal/zephyr-samples/:/elements-sdk/internal/zephyr-samples/
#      - ./internal/zibal/:/elements-sdk/internal/zibal/
# Mount tmp directory for X11 support
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["sleep", "infinity"]
volumes:
  build: {}
