name: 'Nightly Deploy'
description: 'Deploy repository after nightly run.'
inputs:
  repository:
    description: 'Name of repository to deploy to'
    required: true
  branch:
    description: 'Name of the repository branch to deploy to'
    required: false
    default: 'stable'
  PAT:
    description: 'Personal Access Tokane to push to elements repos'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Deploy
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        cd ${{ inputs.repository }}
        git remote add origin https://elements-user:${{ inputs.PAT }}@github.com/aesc-silicon/${{ inputs.repository_name }}.git
        git push origin HEAD:${{ inputs.branch }} -f
        cd ../
      shell: bash
