name: 'Nightly FPGA Test'
description: 'Runs the FPGA flow to generate a SOC and test it'
inputs:
  kit:
    description: 'Name of the kit like Hydrogen1 Nexys4-DDR'
    required: true
  testcase:
    description: 'Name of the test case'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Prepare
      run: |
        ./elements-fpga.py ${{ inputs.kit }} prepare
      shell: bash
    - name: Compile
      run: |
        ./elements-fpga.py ${{ inputs.kit }} compile zephyr zephyr-samples/startup/${{ inputs.testcase }}
      shell: bash
    - name: Generate
      run: |
        ./elements-fpga.py ${{ inputs.kit }} generate
      shell: bash
    - name: Test
      run: |
        ./elements-fpga.py ${{ inputs.kit }} test ${{ inputs.testcase }}
      shell: bash
