name: 'Nightly FPGA Compile'
description: 'Uses the FPGA flow to compile an application.'
inputs:
  kit:
    description: 'Name of the kit like Hydrogen1 Nexys4-DDR'
    required: true
  application:
    description: 'Name of the application'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Prepare
      run: |
        ./elements-fpga.py ${{ inputs.kit }} prepare
      shell: bash
    - name: Compile
      run: |
        ./elements-fpga.py ${{ inputs.kit }} compile zephyr zephyr-samples/demo/${{ inputs.application }}
      shell: bash
    - name: Clean
      run: |
        ./elements.py clean ${{ inputs.kit }}
      shell: bash
