name: SDK documentation

on:
  push:
    paths:
      - '.github/workflows/documentation.yml'
      - 'docsource/*'
  schedule:
  - cron: "0 3 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      branch: gh-pages
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Set-up Environment
      run: |
        pip3 install sphinx
        pip3 install sphinx_rtd_theme

    - name: Build Documenation
      run: |
        mkdir -p docsource/source/docsource/images
        cp docsource/images/*.png docsource/source/docsource/images/
        make clean html -C docsource
        cp -r docsource/build/html/. docs

    - name: Push Documenation to gh-pages
      run: |
        git add docs/
        git config --global user.email "no-mail@phytec.de"
        git config --global user.name "Elements SDK"
        git commit -m "Current docu"
        git push origin HEAD:${{ env.branch }} -f
