name: SDK nightly

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/nightly.yml'
  schedule:
  - cron: "15 4 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

        #- name: Install Packages
        #  run: |
        #    sudo apt install ssh git curl libtool-bin autotools-dev automake pkg-config libyaml-dev
        #    sudo apt install libssl-dev gdb ninja-build
        #    sudo apt install python3 python3.8-dev python3-pip virtualenv openjdk-11-jre-headless
        #    sudo apt install iverilog gtkwave libcanberra-gtk-module libcanberra-gtk3-module

    - name: Set-up Environment
      run: |
        virtualenv -p python3 venv
        python3 elements.py init --manifest next.xml

        #- name: Install SSH Keys
        #  env:
        #    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        #  run: |
        #    ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        #    ssh-add - <<< "${{ secrets.CI_SSH_KEY }}"

    - name: Test Hydrogen1 Nexys4-DDR boot
      uses: actions/nightly-fpga-build
      with:
        kit: "Hydrogen1 Nexys4-DDR"

    - name: Test HydrogenTest Nexys4-DDR boot
      uses: actions/nightly-fpga-build
      with:
        kit: "HydrogenTest Nexys4-DDR"

    - name: Test Hydrogen1 Nexys4-DDR mtimer
      uses: actions/nightly-fpga-test
      with:
        kit: "Hydrogen1 Nexys4-DDR"
        testcase: "mtimer"

    - name: Test HydrogenTest Nexys4-DDR mtimer
      uses: actions/nightly-fpga-test
      with:
        kit: "HydrogenTest Nexys4-DDR"
        testcase: "mtimer"

    - name: Test HydrogenTest Nexys4-DDR gpio
      uses: actions/nightly-fpga-test
      with:
        kit: "HydrogenTest Nexys4-DDR"
        testcase: "gpio"

    - name: Test HydrogenTest Nexys4-DDR uart
      uses: actions/nightly-fpga-test
      with:
        kit: "HydrogenTest Nexys4-DDR"
        testcase: "uart"

    - name: Test HydrogenTest Nexys4-DDR frequency
      uses: actions/nightly-fpga-test
      with:
        kit: "HydrogenTest Nexys4-DDR"
        testcase: "frequency"

    - name: Compile Demo Hydrogen1 Nexys4-DDR leds
      uses: actions/nightly-fpga-compile
      with:
        kit: "Hydrogen1 Nexys4-DDR"
        application: "leds"

    - name: Compile Demo HydrogenTest Nexys4-DDR leds
      uses: actions/nightly-fpga-compile
      with:
        kit: "HydrogenTest Nexys4-DDR"
        application: "leds"

    - name: Deploy openocd
      uses: actions/nightly-deploy
      with:
        repository: "openocd"

    - name: Deploy vexriscv
      uses: actions/nightly-deploy
      with:
        repository: "vexriscv"

    - name: Deploy zephyr
      uses: actions/nightly-deploy
      with:
        repository: "zephyr"

    - name: Deploy embench-iot
      uses: actions/nightly-deploy
      with:
        repository: "embench-iot"
