name: SDK Zephyr nightly

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/nightly-zephyr.yml'
      - '.github/actions/nightly-west-build/action.yml'
  schedule:
  - cron: "15 4 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Install Packages
      run: |
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
        sudo chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
        sudo apt update
        sudo apt install ssh git curl libtool-bin autotools-dev automake pkg-config libyaml-dev
        sudo apt install libssl-dev gdb ninja-build flex bison libfl-dev cmake libftdi1-dev
        sudo apt install python3 python3.10-dev python3-pip virtualenv openjdk-11-jdk-headless
        sudo apt install verilator gtkwave libcanberra-gtk-module libcanberra-gtk3-module
        sudo apt install libtinfo5 libncurses5
        sudo apt install sbt

    - name: Set-up Environment
      working-directory: zephyr/
      run: |
        chmod +x init.sh
        ./init.sh -v -d -f

    - name: Helium1 ECPIX-5 build
      uses: ./.github/actions/nightly-west-build
      with:
        board: "ecpix5/helium1"

    - name: Helium1 ECPIX-5 boot test
      uses: ./.github/actions/nightly-west-test
      with:
        board: "ecpix5/helium1"
        application: "boot"

    - name: Helium1 ECPIX-5 mtimer test
      uses: ./.github/actions/nightly-west-test
      with:
        board: "ecpix5/helium1"
        application: "mtimer"

    - name: Helium1 ECPIX-5 reset test
      uses: ./.github/actions/nightly-west-test
      with:
        board: "ecpix5/helium1"
        application: "reset"
