name: SDK nightly

on:
  schedule:
  - cron: "15 4 * * *"

jobs:
  prepare:
    runs-on: self-hosted
    env:
      repository_name: elements-sdk
    steps:
    - name: clone repo
      run: |
        git clone git@github.com:phytec-labs/${{ env.repository_name }}.git ${{ env.repository_name }}

    - name: set-up environment
      run: |
        cd ${{ env.repository_name }}
        python3 /bin/repo init -u git@github.com:phytec-labs/elements-manifest.git -m next.xml
        python3 /bin/repo sync
        virtualenv -p python3 venv
        . venv/bin/activate
        pip3 install west
        pip3 install -r zephyr/scripts/requirements.txt
        west init -l zephyr
        west update
        # Copy instead of download the toolchain to save bandwidth
        cp /home/inspection/ci/tools/zephyr-sdk/zephyr-toolchain-riscv64-0.12.0-x86_64-linux-setup.run .
        chmod +x zephyr-toolchain-riscv64-0.12.0-x86_64-linux-setup.run
        ./zephyr-toolchain-riscv64-0.12.0-x86_64-linux-setup.run -- -d $PWD/zephyr-sdk-0.12.0 -y -nocmake
        cd ../

    - name: build OpenOCD
      run: |
        cd ${{ env.repository_name }}
        cd openocd
        ./bootstrap
        ./configure
        make || make -j8
        cd ../
        cd ../

  compile_demo:
    runs-on: self-hosted
    needs: [prepare]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        board:
        - "DH-006"
        - "DH-008"
        - "TH-283"
        - "TH-294"
        - "Nexys4-DDR"
        demo:
        - "leds"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements.py compile ${{ matrix.board }} zephyr-samples/demo/${{ matrix.demo }}

  compile_startup:
    runs-on: self-hosted
    needs: [prepare]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        board:
        - "TH-283"
        startup:
        - "frequency"
        - "gpio"
        - "i2c"
        - "mtimer"
        - "spi"
        - "uart"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements.py compile ${{ matrix.board }} zephyr-samples/startup/${{ matrix.startup }}

  compile_arcade:
    runs-on: self-hosted
    needs: [prepare]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        board:
        - "DH-008"
        arcade:
        - "snake"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements.py compile ${{ matrix.board }} zephyr-samples/arcade/${{ matrix.arcade }}

  generate:
    runs-on: self-hosted
    needs: [compile_demo, compile_startup, compile_arcade]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        soc:
        - "DH-006"
        - "TH-294"
        - "Nexys4-DDR"
        - "DH-008"
        - "TH-283"
        - "DH-012"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements.py generate ${{ matrix.soc }}

  test:
    runs-on: self-hosted
    needs: [generate]
    env:
      repository_name: elements-sdk
    steps:
    - name: zibal
      run: |
        cd ${{ env.repository_name }}
        ./elements.py test -zibal

  deploy:
    runs-on: self-hosted
    needs: [test]
    env:
      repository_name: elements-sdk
      branch: stable
    strategy:
      matrix:
        repository:
        - "openocd"
        - "vexriscv"
        - "zephyr"
    steps:
    - name: push back to branch
      run: |
        cd ${{ env.repository_name }}/${{ matrix.repository }}
        git remote add origin git@github.com:phytec-labs/elements-${{ matrix.repository }}.git
        git push origin HEAD:${{ env.branch }} -f
        cd ../../

  cleanup:
    runs-on: self-hosted
    needs: [deploy]
    env:
      repository_name: elements-sdk
    if: always()
    steps:
    - name: post cleanup
      run: |
        rm -rf ${{ env.repository_name}}
