name: SDK nightly

on:
  schedule:
  - cron: "15 4 * * *"

jobs:
  prepare:
    runs-on: self-hosted
    env:
      repository_name: elements-sdk
    steps:
    - name: clone repo
      run: |
        git clone git@github-elements:phytec-labs/${{ env.repository_name }}.git ${{ env.repository_name }}

    - name: set-up environment
      run: |
        cd ${{ env.repository_name }}
        virtualenv -p python3 venv
        python3 elements-fpga.py init --manifest next.xml
        cd ../

  test_boot:
    runs-on: self-hosted
    needs: [prepare]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        kit:
        - "Hydrogen1 Nexys4-DDR"
        - "HydrogenTest Nexys4-DDR"
    steps:
    - name: prepare
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py prepare ${{ matrix.kit }}
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py compile ${{ matrix.kit }} zephyr zephyr-samples/startup/boot
    - name: generate
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py generate ${{ matrix.kit }}
    - name: test
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py test ${{ matrix.kit }} software boot
    - name: synthesize
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py synthesize ${{ matrix.kit }} --toolchain oss

  test_hydrogen1_nexys4-ddr_startup:
    runs-on: self-hosted
    needs: [test_boot]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        kit:
        - "Hydrogen1 Nexys4-DDR"
        startup:
        - "mtimer"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py compile ${{ matrix.kit }} zephyr zephyr-samples/startup/${{ matrix.startup }}
    - name: generate
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py generate ${{ matrix.kit }}
    - name: test
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py test ${{ matrix.kit }} software ${{ matrix.startup }}

  test_hydrogenTest_nexys4-ddr_startup:
    runs-on: self-hosted
    needs: [test_boot]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        kit:
        - "HydrogenTest Nexys4-DDR"
        startup:
        - "mtimer"
        - "gpio"
        - "uart"
        - "frequency"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py compile ${{ matrix.kit }} zephyr zephyr-samples/startup/${{ matrix.startup }}
    - name: generate
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py generate ${{ matrix.kit }}
    - name: test
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py test ${{ matrix.kit }} software ${{ matrix.startup }}

  compile_demo:
    runs-on: self-hosted
    needs: [test_hydrogen1_nexys4-ddr_startup, test_hydrogenTest_nexys4-ddr_startup]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        kit:
        - "Hydrogen1 Nexys4-DDR"
        - "HydrogenTest Nexys4-DDR"
        demo:
        - "leds"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py compile ${{ matrix.kit }} zephyr zephyr-samples/demo/${{ matrix.demo }}

  compile_arcade:
    runs-on: self-hosted
    needs: [test_hydrogen1_nexys4-ddr_startup, test_hydrogenTest_nexys4-ddr_startup]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        kit:
        - "Hydrogen1 Nexys4-DDR"
        - "HydrogenTest Nexys4-DDR"
        arcade:
        - "snake"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements-fpga.py compile ${{ matrix.kit }} zephyr zephyr-samples/arcade/${{ matrix.arcade }}

  deploy:
    runs-on: self-hosted
    needs: [compile_demo, compile_arcade]
    env:
      repository_name: elements-sdk
      branch: stable
    strategy:
      matrix:
        repository:
        - "openocd"
        - "vexriscv"
        - "zephyr"
    steps:
    - name: push back to branch
      run: |
        cd ${{ env.repository_name }}/${{ matrix.repository }}
        git remote add origin git@github-elements:phytec-labs/elements-${{ matrix.repository }}.git
        git push origin HEAD:${{ env.branch }} -f
        cd ../../

  cleanup:
    runs-on: self-hosted
    needs: [deploy]
    env:
      repository_name: elements-sdk
    if: always()
    steps:
    - name: post cleanup
      run: |
        rm -rf ${{ env.repository_name}}
