name: SDK nightly

on:
  schedule:
  - cron: "15 4 * * *"

jobs:
  prepare:
    runs-on: self-hosted
    env:
      repository_name: elements-sdk
    steps:
    - name: clone repo
      run: |
        git clone git@github.com:phytec-labs/${{ env.repository_name }}.git ${{ env.repository_name }}

    - name: set-up environment
      run: |
        cd ${{ env.repository_name }}
        virtualenv -p python3 venv
        python3 elements.py init --manifest next.xml
        cd ../

  compile_demo:
    runs-on: self-hosted
    needs: [prepare]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        board:
        - "DH-006"
        - "DH-008"
        - "TH-283"
        - "TH-294"
        - "Nexys4-DDR"
        demo:
        - "leds"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements.py compile ${{ matrix.board }} zephyr-samples/demo/${{ matrix.demo }}

  compile_startup:
    runs-on: self-hosted
    needs: [prepare]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        board:
        - "TH-283"
        startup:
        - "frequency"
        - "gpio"
        - "i2c"
        - "mtimer"
        - "spi"
        - "uart"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements.py compile ${{ matrix.board }} zephyr-samples/startup/${{ matrix.startup }}

  compile_arcade:
    runs-on: self-hosted
    needs: [prepare]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        board:
        - "DH-008"
        arcade:
        - "snake"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements.py compile ${{ matrix.board }} zephyr-samples/arcade/${{ matrix.arcade }}

  generate:
    runs-on: self-hosted
    needs: [compile_demo, compile_startup, compile_arcade]
    env:
      repository_name: elements-sdk
    strategy:
      matrix:
        soc:
        - "DH-006"
        - "TH-294"
        - "Nexys4-DDR"
        - "DH-008"
        - "TH-283"
        - "DH-012"
    steps:
    - name: compile
      run: |
        cd ${{ env.repository_name }}
        ./elements.py generate ${{ matrix.soc }}

  test:
    runs-on: self-hosted
    needs: [generate]
    env:
      repository_name: elements-sdk
    steps:
    - name: zibal
      run: |
        cd ${{ env.repository_name }}
        ./elements.py test -zibal

  deploy:
    runs-on: self-hosted
    needs: [test]
    env:
      repository_name: elements-sdk
      branch: stable
    strategy:
      matrix:
        repository:
        - "openocd"
        - "vexriscv"
        - "zephyr"
    steps:
    - name: push back to branch
      run: |
        cd ${{ env.repository_name }}/${{ matrix.repository }}
        git remote add origin git@github.com:phytec-labs/elements-${{ matrix.repository }}.git
        git push origin HEAD:${{ env.branch }} -f
        cd ../../

  cleanup:
    runs-on: self-hosted
    needs: [deploy]
    env:
      repository_name: elements-sdk
    if: always()
    steps:
    - name: post cleanup
      run: |
        rm -rf ${{ env.repository_name}}
