name: SDK nightly

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/nightly.yml'
  schedule:
  - cron: "15 4 * * *"

jobs:
  prepare:
    runs-on: self-hosted
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

#    - name: Install Packages
#      run: |
#        sudo apt install ssh git libtool-bin autotools-dev automake pkg-config libyaml-dev
#        sudo apt install python3 python3.8-dev python3-pip virtualenv gdb
#        sudo apt install iverilog gtkwave libcanberra-gtk-module libcanberra-gtk3-module

    - name: set-up environment
      run: |
        virtualenv -p python3 venv
        python3 elements.py init --manifest next.xml

  test_boot:
    runs-on: self-hosted
    needs: [prepare]
    strategy:
      matrix:
        kit:
        - "Hydrogen1 Nexys4-DDR"
        - "HydrogenTest Nexys4-DDR"
    steps:
    - name: prepare
      run: |
        ./elements-fpga.py ${{ matrix.kit }} prepare
    - name: compile
      run: |
        ./elements-fpga.py ${{ matrix.kit }} compile zephyr zephyr-samples/startup/boot
    - name: generate
      run: |
        ./elements-fpga.py ${{ matrix.kit }} generate
    - name: test
      run: |
        ./elements-fpga.py ${{ matrix.kit }} test boot
    - name: synthesize
      run: |
        ./elements-fpga.py ${{ matrix.kit }} synthesize --toolchain oss

  test_hydrogen1_nexys4-ddr_startup:
    runs-on: self-hosted
    needs: [test_boot]
    strategy:
      matrix:
        kit:
        - "Hydrogen1 Nexys4-DDR"
        startup:
        - "mtimer"
    steps:
    - name: compile
      run: |
        ./elements-fpga.py ${{ matrix.kit }} compile zephyr zephyr-samples/startup/${{ matrix.startup }}
    - name: generate
      run: |
        ./elements-fpga.py ${{ matrix.kit }} generate
    - name: test
      run: |
        ./elements-fpga.py ${{ matrix.kit }} test ${{ matrix.startup }}

  test_hydrogenTest_nexys4-ddr_startup:
    runs-on: self-hosted
    needs: [test_boot]
    strategy:
      matrix:
        kit:
        - "HydrogenTest Nexys4-DDR"
        startup:
        - "mtimer"
        - "gpio"
        - "uart"
        - "frequency"
    steps:
    - name: compile
      run: |
        ./elements-fpga.py ${{ matrix.kit }} compile zephyr zephyr-samples/startup/${{ matrix.startup }}
    - name: generate
      run: |
        ./elements-fpga.py ${{ matrix.kit }} generate
    - name: test
      run: |
        ./elements-fpga.py ${{ matrix.kit }} test ${{ matrix.startup }}

  compile_demo:
    runs-on: self-hosted
    needs: [test_hydrogen1_nexys4-ddr_startup, test_hydrogenTest_nexys4-ddr_startup]
    strategy:
      matrix:
        kit:
        - "Hydrogen1 Nexys4-DDR"
        - "HydrogenTest Nexys4-DDR"
        demo:
        - "leds"
    steps:
    - name: compile
      run: |
        ./elements-fpga.py ${{ matrix.kit }} compile zephyr zephyr-samples/demo/${{ matrix.demo }}

#  compile_arcade:
#    runs-on: self-hosted
##    needs: [test_hydrogen1_nexys4-ddr_startup, test_hydrogenTest_nexys4-ddr_startup]
#    needs: [test_hydrogen1_nexys4-ddr_startup]
#    strategy:
#      matrix:
#        kit:
#        - "Hydrogen1 Nexys4-DDR"
##        - "HydrogenTest Nexys4-DDR"
#        arcade:
#        - "snake"
#    steps:
#    - name: compile
#      run: |
#        ./elements-fpga.py compile ${{ matrix.kit }} zephyr zephyr-samples/arcade/${{ matrix.arcade }}

  deploy:
    runs-on: self-hosted
#    needs: [compile_demo, compile_arcade]
    needs: [compile_demo]
    env:
      branch: stable
    strategy:
      matrix:
        repository:
        - "openocd"
        - "vexriscv"
        - "zephyr"
        - "embench-iot"
    steps:
    - name: push back to branch
      run: |
        cd ${{ matrix.repository }}
        git remote add origin git@github-elements:phytec-labs/elements-${{ matrix.repository }}.git
        git push origin HEAD:${{ env.branch }} -f
        cd ../

  cleanup:
    runs-on: self-hosted
    needs: [deploy]
    if: always()
    steps:
    - name: post cleanup
      run: |
        ls -A1 | xargs rm -rf
