name: SDK nightly

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/nightly.yml'
      - '.github/actions/nightly-deploy/action.yml'
      - '.github/actions/nightly-fpga-build/action.yml'
      - '.github/actions/nightly-fpga-compile/action.yml'
      - '.github/actions/nightly-fpga-test/action.yml'
  schedule:
  - cron: "15 4 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Install Packages
      run: |
        sudo apt update
        sudo apt install ssh git curl libtool-bin autotools-dev automake pkg-config libyaml-dev
        sudo apt install libssl-dev gdb ninja-build flex bison libfl-dev
        sudo apt install python3 python3.8-dev python3-pip virtualenv openjdk-11-jdk-headless
        sudo apt install verilator gtkwave libcanberra-gtk-module libcanberra-gtk3-module

    - name: Set-up Environment
      run: |
        virtualenv -p python3 venv
        python3 elements.py init --manifest next.xml

    - name: Debugging
      run: |
        echo $PWD
        ls -lh
        cd internal && ./repo info

    - name: Test Hydrogen1 Nexys4-DDR boot
      uses: ./.github/actions/nightly-fpga-test
      with:
        kit: "Hydrogen1 Nexys4-DDR"
        testcase: "boot"

    - name: Test HydrogenTest Nexys4-DDR boot
      uses: ./.github/actions/nightly-fpga-test
      with:
        kit: "HydrogenTest Nexys4-DDR"
        testcase: "boot"

    - name: Test Hydrogen1 Nexys4-DDR mtimer
      uses: ./.github/actions/nightly-fpga-test
      with:
        kit: "Hydrogen1 Nexys4-DDR"
        testcase: "mtimer"

    - name: Test HydrogenTest Nexys4-DDR mtimer
      uses: ./.github/actions/nightly-fpga-test
      with:
        kit: "HydrogenTest Nexys4-DDR"
        testcase: "mtimer"

# Verilator does not simulate IOBUFs correct. Only first works.
#    - name: Test HydrogenTest Nexys4-DDR gpio
#      uses: ./.github/actions/nightly-fpga-test
#      with:
#        kit: "HydrogenTest Nexys4-DDR"
#        testcase: "gpio"

    - name: Test HydrogenTest Nexys4-DDR uart
      uses: ./.github/actions/nightly-fpga-test
      with:
        kit: "HydrogenTest Nexys4-DDR"
        testcase: "uart"

    - name: Test HydrogenTest Nexys4-DDR frequency
      uses: ./.github/actions/nightly-fpga-test
      with:
        kit: "HydrogenTest Nexys4-DDR"
        testcase: "frequency"

    - name: Compile Demo Hydrogen1 Nexys4-DDR leds
      uses: ./.github/actions/nightly-fpga-compile
      with:
        kit: "Hydrogen1 Nexys4-DDR"
        application: "leds"

    - name: Compile Demo HydrogenTest Nexys4-DDR leds
      uses: ./.github/actions/nightly-fpga-compile
      with:
        kit: "HydrogenTest Nexys4-DDR"
        application: "leds"

    - name: Deploy openocd
      uses: ./.github/actions/nightly-deploy
      with:
        repository: "openocd"
        PAT: ${{ secrets.PAT }}

    - name: Deploy vexriscv
      uses: ./.github/actions/nightly-deploy
      with:
        repository: "vexriscv"
        PAT: ${{ secrets.PAT }}

    - name: Deploy zephyr
      uses: ./.github/actions/nightly-deploy
      with:
        repository: "zephyr"
        PAT: ${{ secrets.PAT }}

    - name: Deploy embench-iot
      uses: ./.github/actions/nightly-deploy
      with:
        repository: "embench-iot"
        PAT: ${{ secrets.PAT }}
